### 📐 Tính Toán Gradient Cục Bộ Trên Ảnh Xám

#### 1. Khái niệm Gradient trong xử lý ảnh
Gradient trong ảnh xám là một đại lượng vector biểu thị **mức độ thay đổi cường độ sáng** tại một điểm ảnh.  
Nói cách khác, gradient cho biết **mức độ biến thiên và hướng thay đổi** của độ sáng — thường được dùng để **phát hiện biên (edge detection)** trong ảnh.

Gradient gồm hai thành phần:
- \( G_x \): độ biến thiên theo **trục ngang (x)**  
- \( G_y \): độ biến thiên theo **trục dọc (y)**  

Từ đó, **độ lớn gradient** được tính bằng công thức:
$$
|G| = \sqrt{G_x^2 + G_y^2}
$$
và **hướng gradient** (góc nghiêng của biên) là:
$$
\theta = \arctan\left(\frac{G_y}{G_x}\right)
$$

---

#### 2. Cách tính trong đoạn mã
Trong ví dụ, ma trận ảnh xám \( A \) kích thước **3x3** được tạo thủ công:
\[
A =
\begin{bmatrix}
25 & 50 & 50 \\
20 & 40 & 49 \\
22 & 36 & 36
\end{bmatrix}
\]

Tại điểm **trung tâm (1,1)**, gradient được ước lượng bằng **hiệu số cường độ giữa các điểm kề**:
- \( G_x = A[1,2] - A[1,0] \) → sự thay đổi theo chiều ngang  
- \( G_y = A[2,1] - A[0,1] \) → sự thay đổi theo chiều dọc  

Công thức này tương đương với **phép lấy đạo hàm rời rạc (finite difference)** — một kỹ thuật cơ bản trong xử lý ảnh số để xấp xỉ đạo hàm liên tục.

---

#### 3. Nhận xét kết quả
Kết quả in ra gồm:
- Ma trận giá trị ảnh gốc.  
- Giá trị **gradient theo trục x (Gx)** và **trục y (Gy)**.  
- **Độ lớn gradient trung tâm** – biểu thị cường độ biên tại điểm đó.

Nếu độ lớn gradient cao, có thể suy ra **biên hoặc vùng chuyển sắc mạnh** tại vị trí đó.  
Ngược lại, nếu gradient gần 0, khu vực này có thể là vùng **đồng nhất (uniform region)**.

---

#### 4. Ứng dụng mở rộng
Kỹ thuật tính gradient này là **nền tảng của nhiều thuật toán xử lý ảnh**, bao gồm:
- **Phát hiện biên Sobel, Prewitt, Canny**  
- **Phát hiện góc (corner detection)**  
- **Tăng cường độ tương phản địa phương**  
- **Tính toán hướng gradient trong HOG (Histogram of Oriented Gradients)**  

Việc hiểu rõ gradient cục bộ giúp nắm vững cách máy tính “cảm nhận” sự thay đổi cấu trúc trong hình ảnh.


In [ ]:
import numpy as np

# Ma trận ảnh xám 3x3 tự tạo
A = np.array([[25, 50, 50],
              [20, 40, 49],
              [22, 36, 36]])

# Tính gradient tại điểm trung tâm (1,1)

Gx = (A[1,2]) - (A[1,0])
Gy = (A[2,1]) - (A[0,1])

print("Ma trận A:")
print(A)
print("Gradient theo trục x tại điểm trung tâm:", Gx)
print("Gradient theo trục y tại điểm trung tâm:", Gy)
print("Độ lớn gradient trung tâm:", np.sqrt(Gx**2 + Gy**2))



Ma trận A:
[[25 50 50]
 [20 40 49]
 [22 36 36]]
Gradient theo trục x tại điểm trung tâm: 29
Gradient theo trục y tại điểm trung tâm: -14
Độ lớn gradient trung tâm: 32.202484376209235


In [ ]:
import numpy as np

B = np.array([[125,130,150],
              [200,190,167],
              [222,156,236]])

Gx = (B[1,2]) - (B[1,0])
Gy = (B[2,1]) - (B[0,1])

print("Ma trận B:")
print(B)
print("Gradient theo trục x tại điểm trung tâm:", Gx)
print("Gradient theo trục y tại điểm trung tâm:", Gy)
print("Độ lớn gradient trung tâm:", np.sqrt(Gx**2 + Gy**2))

Ma trận B:
[[125 130 150]
 [200 190 167]
 [222 156 236]]
Gradient theo trục x tại điểm trung tâm: -33
Gradient theo trục y tại điểm trung tâm: 26
Độ lớn gradient trung tâm: 42.01190307520001
